
.feature string_escapes +
.charmap '#', $c0 ; lb symbol
.charmap '$', $c2
.charmap '%', $c3 ; .00 symbol 
.charmap '_', $c6
.charmap $27, $c7 ; single quote '
.charmap '-', $ca
.charmap '"', $cb
.charmap ';', $cc
.charmap '(', $ce
.charmap ')', $cf
.charmap 'A', $d0
.charmap 'a', $d0
.charmap 'B', $d1
.charmap 'b', $d1
.charmap 'C', $d2
.charmap 'c', $d2
.charmap 'D', $d3
.charmap 'd', $d3
.charmap 'E', $d4
.charmap 'e', $d4
.charmap 'F', $d5
.charmap 'f', $d5
.charmap 'G', $d6
.charmap 'g', $d6
.charmap 'H', $d7
.charmap 'h', $d7
.charmap 'I', $d8
.charmap 'i', $d8
.charmap 'J', $d9
.charmap 'j', $d9
.charmap 'K', $da
.charmap 'k', $da
.charmap 'L', $db
.charmap 'l', $db
.charmap 'M', $dc
.charmap 'm', $dc
.charmap 'N', $dd
.charmap 'n', $dd
.charmap 'P', $de
.charmap 'p', $de
.charmap 'Q', $df
.charmap 'q', $df
.charmap 'R', $e0
.charmap 'r', $e0
.charmap 'S', $e1
.charmap 's', $e1
.charmap 'T', $e2
.charmap 't', $e2
.charmap 'U', $e3
.charmap 'u', $e3
.charmap 'V', $e4
.charmap 'v', $e4
.charmap 'W', $e5
.charmap 'w', $e5
.charmap 'X', $e6
.charmap 'x', $e6
.charmap 'Y', $e7
.charmap 'y', $e7
.charmap 'Z', $e8
.charmap 'z', $e8
.charmap 'O', $e9
.charmap 'o', $e9
.charmap '0', $e9
.charmap '1', $ea
.charmap '2', $eb
.charmap '3', $ec
.charmap '4', $ed
.charmap '5', $ee
.charmap '6', $ef
.charmap '7', $f0
.charmap '8', $f1
.charmap '9', $f2
.charmap ':', $f3
.charmap ',', $f4
.charmap '.', $f5
.charmap '!', $f6
.charmap '?', $f7
.charmap ' ', $ff
